// src/Redux/Admin/ActionType.js

export const FETCH_RENT_OUT_PRODUCTS_REQUEST = "FETCH_RENT_OUT_PRODUCTS_REQUEST";
export const FETCH_RENT_OUT_PRODUCTS_SUCCESS = "FETCH_RENT_OUT_PRODUCTS_SUCCESS";
export const FETCH_RENT_OUT_PRODUCTS_FAILURE = "FETCH_RENT_OUT_PRODUCTS_FAILURE";

export const APPROVE_RENT_OUT_PRODUCT_REQUEST = "APPROVE_RENT_OUT_PRODUCT_REQUEST";
export const APPROVE_RENT_OUT_PRODUCT_SUCCESS = "APPROVE_RENT_OUT_PRODUCT_SUCCESS";
export const APPROVE_RENT_OUT_PRODUCT_FAILURE = "APPROVE_RENT_OUT_PRODUCT_FAILURE";

export const REJECT_RENT_OUT_PRODUCT_REQUEST = "REJECT_RENT_OUT_PRODUCT_REQUEST";
export const REJECT_RENT_OUT_PRODUCT_SUCCESS = "REJECT_RENT_OUT_PRODUCT_SUCCESS";
export const REJECT_RENT_OUT_PRODUCT_FAILURE = "REJECT_RENT_OUT_PRODUCT_FAILURE";

// Add the following action types for customer rent-out actions
export const RENT_OUT_ITEM_REQUEST = "RENT_OUT_ITEM_REQUEST";
export const RENT_OUT_ITEM_SUCCESS = "RENT_OUT_ITEM_SUCCESS";
export const RENT_OUT_ITEM_FAILURE = "RENT_OUT_ITEM_FAILURE";

// Add any additional action types as needed
