// actionTypes.js

export const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

export const FETCH_RENT_OUTS_REQUEST = 'FETCH_RENT_OUTS_REQUEST';
export const FETCH_RENT_OUTS_SUCCESS = 'FETCH_RENT_OUTS_SUCCESS';
export const FETCH_RENT_OUTS_FAILURE = 'FETCH_RENT_OUTS_FAILURE';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';