// src/Redux/Admin/adminActionTypes.js

export const FETCH_RENT_OUT_PRODUCTS_REQUEST = 'FETCH_RENT_OUT_PRODUCTS_REQUEST';
export const FETCH_RENT_OUT_PRODUCTS_SUCCESS = 'FETCH_RENT_OUT_PRODUCTS_SUCCESS';
export const FETCH_RENT_OUT_PRODUCTS_FAILURE = 'FETCH_RENT_OUT_PRODUCTS_FAILURE';

export const APPROVE_RENT_OUT_PRODUCT_REQUEST = 'APPROVE_RENT_OUT_PRODUCT_REQUEST';
export const APPROVE_RENT_OUT_PRODUCT_SUCCESS = 'APPROVE_RENT_OUT_PRODUCT_SUCCESS';
export const APPROVE_RENT_OUT_PRODUCT_FAILURE = 'APPROVE_RENT_OUT_PRODUCT_FAILURE';

export const REJECT_RENT_OUT_PRODUCT_REQUEST = 'REJECT_RENT_OUT_PRODUCT_REQUEST';
export const REJECT_RENT_OUT_PRODUCT_SUCCESS = 'REJECT_RENT_OUT_PRODUCT_SUCCESS';
export const REJECT_RENT_OUT_PRODUCT_FAILURE = 'REJECT_RENT_OUT_PRODUCT_FAILURE';

// actionTypes.js
export const FETCH_RENTOUT_PRODUCT_DETAIL_REQUEST = 'FETCH_RENTOUT_PRODUCT_DETAIL_REQUEST';
export const FETCH_RENTOUT_PRODUCT_DETAIL_SUCCESS = 'FETCH_RENTOUT_PRODUCT_DETAIL_SUCCESS';
export const FETCH_RENTOUT_PRODUCT_DETAIL_FAILURE = 'FETCH_RENTOUT_PRODUCT_DETAIL_FAILURE';

export const APPROVE_RENTOUT_PRODUCT_SUCCESS = 'APPROVE_RENTOUT_PRODUCT_SUCCESS';
export const REJECT_RENTOUT_PRODUCT_SUCCESS = 'REJECT_RENTOUT_PRODUCT_SUCCESS';

